const translations = {
  it: {
    nav_profile: "Profilo",
    nav_experience: "Esperienze",
    nav_projects: "Progetti",
    nav_contact: "Contatti",
    header_cta: "Contatta",
    hero_location: "Cortemilia (IT) - San Francisco (USA)",
    hero_title: "Sales, hospitality e progetti tra Italia e Stati Uniti.",
    hero_text:
      "Esperienza internazionale in sales management, ospitalita e business development tra USA, Europa e Africa. Lavoro su crescita commerciale, partnership e posizionamento di brand premium con un approccio pratico e orientato al risultato.",
    hero_email: "Contattami via email",
    hero_cv: "Scarica CV",
    availability_label: "Disponibilita",
    availability_text: "Collaborazioni, consulenze e nuovi progetti.",
    profile_eyebrow: "Executive profile",
    profile_title: "Un profilo commerciale con mentalita operativa.",
    profile_text:
      "Porto valore quando un progetto deve crescere: trovare clienti, costruire fiducia, negoziare bene, coordinare operazioni e trasformare un posizionamento premium in risultati misurabili.",
    metric_one_value: "USA / Europa / Africa",
    metric_one_label: "Esperienza internazionale",
    metric_two_value: "Multi-milioni",
    metric_two_label: "Crescita fatturato USA in 2 anni",
    metric_three_value: "500+ ospiti",
    metric_three_label: "Eventi luxury e corporate",
    experience_eyebrow: "Esperienze",
    experience_title: "Ruoli e risultati principali.",
    exp_1_date: "Giu 2025 - Presente",
    exp_1_title: "Sales Executive - Service Engineer",
    exp_1_text:
      "Sviluppo nuove opportunita, gestione end-to-end del ciclo di vendita, supporto tecnico-commerciale e presenza a fiere di settore.",
    exp_2_date: "Lug 2022 - Mag 2025",
    exp_2_title: "Vice President - Sales Manager",
    exp_2_text:
      "Espansione USA da quasi zero a fatturato multi-milionario, gestione account strategici e crescita dei clienti di ritorno del 40% YoY.",
    exp_3_date: "2021 - 2022",
    exp_3_title: "Purchasing Manager",
    exp_3_text:
      "Procurement di materie prime premium, negoziazione fornitori tra Italia, Turchia e California e supporto a sviluppo prodotto.",
    exp_4_date: "2016 - 2021",
    exp_4_title: "Hospitality, Events & Project Consulting",
    exp_4_company: "Italia / International",
    exp_4_text:
      "Aperture ristorative, eventi istituzionali e luxury hospitality, incluso supporto a progetti internazionali con Chef Carlo Zarri.",
    exp_5_date: "Gen 2021 - Presente",
    exp_5_title: "Founder & Project Manager",
    exp_5_text:
      "Progetto agro-turistico sostenibile con modello di adozione nocciolo, sponsorship e promozione del territorio tramite marketing ed eventi internazionali.",
    exp_6_date: "Nov 2020 - Gen 2021",
    exp_6_title: "Restaurant Opening Consultant",
    exp_6_text:
      "Consulenza per apertura di tre ristoranti: sourcing fornitori, layout cucina, procurement, recruiting, training e workflow per posizionamento luxury.",
    exp_7_date: "Mag 2019 - Giu 2019",
    exp_7_title: "Event Manager",
    exp_7_text:
      "Organizzazione di eventi istituzionali, gestione procurement, logistica, sicurezza e hospitality in protocollo diplomatico.",
    projects_eyebrow: "Progetti in sviluppo",
    projects_title: "Iniziative con potenziale scalabile.",
    americando_type: "Podcast - Host & Founder",
    americando_text:
      "Un podcast che racconta l'America agli italiani con un taglio pratico: visti, tax, contratti, storie imprenditoriali, studenti e giovani founder.",
    project_instagram: "Instagram",
    plin_type: "Pasta bar a Miami - in apertura",
    plin_text:
      "Format veloce, curato e scalabile: pochi piatti, ingredienti ottimi, servizio rapido, controllo food cost e attenzione alla customer experience.",
    project_partnership: "Partnership",
    skills_eyebrow: "Competenze",
    skills_title: "Dove porto valore.",
    skill_sales_title: "Sales & Growth",
    skill_sales_text: "International sales, market expansion, business development e strategic account management.",
    skill_ops_title: "Hospitality & Operations",
    skill_ops_text: "Procurement, vendor relations, event management, team leadership e customer experience.",
    skill_tools_title: "Strumenti & Lingue",
    skill_tools_text: "CRM tools, Microsoft Office, Google Workspace. Italiano madrelingua, inglese B2, francese base.",
    contact_eyebrow: "Contatti",
    contact_title: "Parliamo del prossimo progetto.",
    contact_text: "Per collaborazioni, consulenze, eventi o partnership commerciali, scrivimi direttamente.",
    contact_cv: "CV PDF",
    footer_top: "Torna su",
  },
  en: {
    nav_profile: "Profile",
    nav_experience: "Experience",
    nav_projects: "Projects",
    nav_contact: "Contact",
    header_cta: "Contact",
    hero_location: "Cortemilia (IT) - San Francisco (USA)",
    hero_title: "Sales, hospitality and projects between Italy and the United States.",
    hero_text:
      "International experience in sales management, hospitality and business development across the USA, Europe and Africa. I work on commercial growth, partnerships and premium brand positioning with a practical, result-oriented approach.",
    hero_email: "Contact by email",
    hero_cv: "Download CV",
    availability_label: "Availability",
    availability_text: "Collaborations, consulting and new projects.",
    profile_eyebrow: "Executive profile",
    profile_title: "A commercial profile with an operating mindset.",
    profile_text:
      "I create value when a project needs to grow: finding clients, building trust, negotiating well, coordinating operations and turning premium positioning into measurable results.",
    metric_one_value: "USA / Europe / Africa",
    metric_one_label: "International experience",
